from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from uuid import UUID
from datetime import datetime

# --- Authentication Schemas ---

class OTPRequest(BaseModel):
    email: str = Field(..., description="Email address requesting the code")

class OTPVerify(BaseModel):
    email: str = Field(..., description="Email address linked to the OTP")
    otp: str = Field(..., min_length=6, max_length=6, description="6-digit numeric verification code")

class UserRegister(BaseModel):
    email: str = Field(..., description="Email address for registration")
    password: str = Field(..., min_length=6, description="Password (minimum 6 characters)")
    name: str = Field(..., description="Full name or organization name")
    otp: str = Field(..., min_length=6, max_length=6, description="6-digit email verification code")
    role: Optional[str] = Field("recruiter", description="Default role: recruiter or admin")

class RegisterOTPRequest(BaseModel):
    email: str = Field(..., description="Email address requesting registration code")

class UserLogin(BaseModel):
    email: str = Field(..., description="Login email address")
    password: str = Field(..., description="Login password")

class CandidateCheckin(BaseModel):
    token: str = Field(..., description="Job invite token")
    email: str = Field(..., description="Candidate email address")
    first_name: str = Field(..., description="Candidate first name")
    last_name: str = Field(..., description="Candidate last name")
    resume_url: Optional[str] = Field(None, description="Optional link to resume")

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    role: str

# --- Job Schemas ---

class JobCreate(BaseModel):
    title: str = Field(..., min_length=2, max_length=255, description="Job listing title")
    description: str = Field(..., description="Full description of duties and roles")
    requirements: Optional[str] = Field(None, description="Legacy parameter")
    questions: List[str] = Field(default_factory=list, description="Array of assessment prompts")

class JobUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    requirements: Optional[str] = None
    questions: Optional[List[str]] = None
    is_active: Optional[bool] = None

class JobResponse(BaseModel):
    id: UUID
    title: str
    description: str
    requirements: Optional[str]
    questions: Optional[List[str]] = None
    created_by: Optional[UUID]
    token: Optional[str] = None
    is_active: Optional[bool] = True
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

# --- Submission & Upload Schemas ---

class PresignedUrlRequest(BaseModel):
    filename: str = Field(..., description="The name of the video or resume file to upload")
    content_type: Optional[str] = Field(None, description="The MIME type of the file, e.g. video/mp4")

class PresignedUrlResponse(BaseModel):
    upload_url: str = Field(..., description="Presigned PUT URL generated by Cloudflare R2")
    object_key: str = Field(..., description="Unique filename storage path in the bucket")

class SubmissionCreate(BaseModel):
    job_id: UUID = Field(..., description="The ID of the job being applied for")
    candidate_email: str = Field(..., description="Email of the candidate submitting details")
    candidate_first_name: str = Field(..., description="First name of candidate")
    candidate_last_name: str = Field(..., description="Last name of candidate")
    video_url: str = Field(..., description="R2 video url location containing the response")

class SubmissionResponse(BaseModel):
    id: UUID
    job_id: UUID
    candidate_id: UUID
    video_url: Optional[str]
    status: str
    score_communication: Optional[int]
    score_technical: Optional[int]
    score_telemetry: Optional[int]
    ai_feedback: Optional[Dict[str, Any]]
    created_at: datetime

    class Config:
        from_attributes = True

# --- Webhook Schemas ---

class PaddleWebhookPayload(BaseModel):
    event_type: str = Field(..., description="The Paddle event name e.g. subscription.created")
    data: Dict[str, Any] = Field(..., description="Paddle resource payload details")
    signature: str = Field(..., description="The verification signature for this webhook event")

# --- Administrative Schemas ---

class AdminDashboardStats(BaseModel):
    total_users: int
    total_jobs: int
    total_candidates: int
    total_submissions: int
    submissions_by_status: Dict[str, int]
